# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Minimal
email: blog@minimal.com
description: "Enfim estudano Jekyll :D"
baseurl: "/minimal-blog" # the subpath of your site, e.g. /blog
url: "/minimal-blog" # the base hostname & protocol for your site
twitter_username: minimal_twitter
github_username:  minimal_github

# Build settings
markdown: kramdown
# permalink: /:categories/:year/:month/:day/:title
permalink: /:title
